Brain-Development-and-Disorders-Lab/mars

- .github/workflows/deploy.yml
- client/src/database/functions.ts
- client/src/pages/Create/Attribute.tsx
- client/src/pages/Create/Collection.tsx
- client/src/pages/Create/Entity.tsx
- server/package.json
- server/src/database/connection.ts
- server/src/operations/Attributes.ts
- server/src/operations/Collections.ts
- server/src/operations/Entities.ts
- server/tsconfig.json
- server/yarn.lock
- Identifier is shorter (8 characters, including `a`, `e`, or `c` prepended)
- Uses an external library `nanoid`
> Update internal identifier

- client/src/components/AttributeCard/index.tsx
- client/src/components/Navigation/index.tsx
- client/src/components/PageContainer/index.tsx
- client/src/components/Parameter/index.tsx
- client/src/components/ParameterGroup/index.tsx
- client/src/components/SearchBox/index.tsx
- client/src/pages/View/Entity.tsx
- client/src/styles/theme.ts
- server/src/operations/Entities.ts
- server/test/Entities.test.ts
- types/index.d.ts
- Improve Entity test coverage
- Update Parameter view
> Enable Attribute editing

- client/src/components/AttributeCard/index.tsx
- client/src/components/Container/index.tsx
- client/src/components/DataTable/index.tsx
- client/src/components/Icon/index.tsx
- client/src/components/SearchBox/index.tsx
- client/src/components/Values/index.tsx
- client/src/pages/Attribute.tsx
- client/src/pages/Attributes.tsx
- client/src/pages/Collection.tsx
- client/src/pages/Collections.tsx
- client/src/pages/Create.tsx
- client/src/pages/Dashboard.tsx
- client/src/pages/Entities.tsx
- client/src/pages/Entity.tsx
- client/src/pages/Search.tsx
- client/src/styles/theme.ts
- types/index.d.ts
- Streamline use of components
- Rename some props
- Fix ID and data propagation bugs
> Update interface and spacing

- client/src/pages/Create.tsx
- client/src/pages/Entity.tsx
- server/src/database/connection.ts
- server/src/operations/Entities.ts
- server/src/operations/System.ts
- server/test/Entities.test.ts
- types/index.d.ts
Addresses Jira issue: MARS-1-entity-attachments
- Support image uploads
- Associate image uploads with Entities
- Remove associated images (but preserve on server)
> Initial functionality to manage Entity attachments

- server/src/operations/Entities.ts
* Temporarily disable edit locking until a wider version control and access control system is implemented
> MARS-50-disable-edit-locking

- client/src/components/SearchBox/index.tsx
- client/src/pages/Search.tsx
- client/src/pages/view/Attribute.tsx
- client/src/pages/view/Collection.tsx
- client/src/pages/view/Entity.tsx
* Fix spacing and borders on Entity, Collection, and Attribute views
* Fix bugs with Search navigating to Entities
> MARS-51-Update-user-interface-spacing-and-organization

- client/src/components/Icon/index.tsx
- client/src/components/Preview/index.tsx
- client/src/pages/view/Entity.tsx
- types/index.d.ts
* Add basic zoom and rotate controls to image previews
> MARS-52-manipulate-image-attachments

- README.md
- client/src/index.html
- client/src/pages/Login.tsx
- client/src/variables.ts
- server/src/index.ts
- server/src/operations/Authentication.ts
* Use updated `reusable.bio` URL
* Update API endpoints
> RBIO-53-Rebrand-application-to-reusable.bio

- client/src/pages/Dashboard.tsx
- client/src/pages/view/Entities.tsx
- server/src/operations/System.ts
* Fix importing "date" and "select" type Values by adding data cleaning steps
* Update Dashboard components to show loading indicators or messages depending on the loading state and whether the components contain content or not
> MARS-66-Spreadsheet-imports-missing-date-values-and-Select-values

- client/src/components/AttributePreview/index.tsx
- client/src/components/DataTable/index.tsx
- client/src/components/Navigation/index.tsx
- client/src/components/Values/index.tsx
- client/src/pages/Dashboard.tsx
- client/src/pages/Search.tsx
- client/src/pages/create/Project.tsx
- client/src/pages/view/Attribute.tsx
- client/src/pages/view/Attributes.tsx
- client/src/pages/view/Entities.tsx
- client/src/pages/view/Entity.tsx
- client/src/pages/view/Project.tsx
- client/src/pages/view/Projects.tsx
- server/src/operations/Entities.ts
- server/src/routes/Entities.ts
- types/index.d.ts
* Adds functionality to export multiple different Entities simultaneously from the `Entities` page.
* Adds `actions` to the `DataTable` components, allowing actions to be performed on multiple rows.
> MARS-67-Create-action-drop-down-for-DataTable-component

- server/package.json
- server/yarn.lock
* Apply security updates to server packages.
> MARS-70-Apply-security-updates

- client/src/App.tsx
- client/src/components/DataTable/index.tsx
- client/src/components/Importer/index.tsx
- client/src/components/Navigation/index.tsx
- client/src/components/Preview/index.tsx
- client/src/components/SearchBox/index.tsx
- client/src/components/Values/index.tsx
- client/src/database/functions.ts
- client/src/pages/Dashboard.tsx
- client/src/pages/Login.tsx
- client/src/pages/Search.tsx
- client/src/pages/create/Attribute.tsx
- client/src/pages/create/Entity.tsx
- client/src/pages/create/Project.tsx
- client/src/pages/view/Entities.tsx
- client/src/pages/view/Entity.tsx
- client/src/pages/view/Project.tsx
- client/src/pages/view/Projects.tsx
* Integrate `DataTable` component
* Create "Export Entities" action for search results
> MARS-71-Add-action-drop-down-to-search-results

- .github/pull_request_template.md
Please include a summary of the change and the work item associated with it.
Please include link to Jira/AzureDevops etc
> [Mars robin 1] initial test commit and new PR template

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/test.yml
enabling manual trigger of github actions
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/162/
> [MARS-162] enabling manual github action trigger

- .github/workflows/test.yml
- .github/workflows/test_cypress.yml
- README.md
- cypress.config.js
- cypress/e2e/launch.spec.cy.ts
- cypress/fixtures/example.json
- cypress/support/commands.js
- cypress/support/e2e.js
- package.json
- tsconfig.json
- yarn.lock
Please include a summary of the change and the work item associated with it.
[Please include link to Jira/AzureDevops etc
](https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/156)
$> yarn run cypress
> [MARS-156]  add cypress support

- .github/workflows/build_and_test.yml
- client/src/components/Label/Warning.test.tsx
update github action to run client test
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/188
> [MARS-188] update github action to run client test

- server/package.json
- server/src/index.ts
- server/src/operations/Projects.ts
- server/yarn.lock
adding source map support
add yarn buildDev
add startDev for server
add minor defensive code on export feature
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/199
> [MARS-199]adding source map support, add dev build and dev start for server

- client/src/components/Graph/index.tsx
- client/src/components/Importer/index.tsx
- client/src/pages/view/Entity.tsx
- client/src/pages/view/Project.tsx
- cypress/e2e/import_CSV.spec.cy.ts
- cypress/fixtures/export_entities.csv
- server/src/operations/Entities.ts
- server/src/operations/System.ts
adding origin/product will be uniq by name
on import page, some field will have default value to be faster
add several defensive code
https://dev.azure.com/gt-sse-center/MARS%202023/_sprints/backlog/MARS%202023%20Team/MARS%202023/Sprint%202?workitem=201
box1 has minibox 1 as product
mini box 1 has box 1 as origin
> [MARS-201] import now save the origin and product

- client/package.json
- client/src/App.tsx
- client/src/pages/QueryBuilderTab.tsx
- client/src/pages/Search.tsx
- client/src/styles/styles.css
- client/yarn.lock
- server/src/operations/Search.ts
- server/src/routes/Search.ts
this PR is part 1 of 3
add QueryBuilder
put existing query in new file
added backend to handle built query
part 2 and 3 will add testing and improve design and cleanup (remove) existing broken query functions (they are not removed yet to compare regressive testing and to compare design etc etc).
https://dev.azure.com/gt-sse-center/MARS%202023/_sprints/backlog/MARS%202023%20Team/MARS%202023/Sprint%203?workitem=133
> [MARS-212] add QueryBuilder, put existing query in new file, added backend to handle built query

- client/src/pages/QueryBuilderTab.tsx
- client/src/styles/styles.css
STEP 2 out of 3
improve default design of the query builder.
https://dev.azure.com/gt-sse-center/MARS%202023/_sprints/backlog/MARS%202023%20Team/MARS%202023/Sprint%203?workitem=133
> [MARS-213] updated design of the query builder

- client/jest.config.js
- client/package.json
- client/src/pages/QueryBuilderTab.test.tsx
- client/src/pages/QueryBuilderTab.tsx
- client/yarn.lock
- cypress/e2e/query_builder.spec.cy.ts
Fixing test config file
adding simple unit test
adding cypress test that check query return value
[Please include link to Jira/AzureDevops etc
](https://dev.azure.com/gt-sse-center/MARS%202023/_sprints/taskboard/MARS%202023%20Team/MARS%202023/Sprint%203?workitem=214)
> [MARS-214] update jets config file and and tests for QueryBuilderTab

- client/src/components/DataTable/index.tsx
- client/src/pages/view/Entities.tsx
- client/src/pages/view/Project.tsx
- server/src/operations/Entities.ts
- server/src/operations/Projects.ts
- server/src/routes/Entities.ts
- server/test/Entities.test.ts
Export all entities feature
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/224
> [MARS-224] Export all entities feature

- .github/workflows/build_and_test.yml
- client/src/components/Importer/index.tsx
- cypress/e2e/2_2_import_JSON.spec.cy.ts
- cypress/fixtures/export_entities.csv
- cypress/fixtures/export_entities.json
- package.json
- server/package.json
- server/src/operations/Entities.ts
- server/src/operations/Projects.ts
- server/src/operations/System.ts
- server/src/routes/System.ts
Import JSON is now supported
if entity ID is set, it will update the entity
https://dev.azure.com/gt-sse-center/MARS%202023/_sprints/backlog/MARS%202023%20Team/MARS%202023/Sprint%206?workitem=137
https://dev.azure.com/gt-sse-center/MARS%202023/_sprints/backlog/MARS%202023%20Team/MARS%202023/Sprint%206?workitem=141
> [MARS-137] importJSON fix and add entity mapping by ID

- server/test/Entities.test.ts
getDataMultiple now use mongodb built in fetch
[Please include link to Jira/AzureDevops etc
](https://dev.azure.com/gt-sse-center/MARS%202023/_sprints/backlog/MARS%202023%20Team/MARS%202023/Sprint%206?workitem=208)
> [MARS-208] refactor / improve speed getDataMultiple

- client/src/App.tsx
- client/src/pages/view/Project.tsx
- client/src/util.ts
- client/src/variables.ts
- client/webpack.dev.js
- cypress/e2e/2_2_import_JSON.spec.cy.ts
- cypress/fixtures/export_entities.json
- server/src/index.ts
- server/src/middleware/authMiddleware.ts
- server/src/operations/Attributes.ts
- server/src/operations/Authentication.ts
- server/src/operations/Search.ts
- server/src/operations/System.ts
- server/src/operations/Users.ts
- server/src/routes/Activity.ts
- server/src/routes/Attributes.ts
- server/src/routes/Entities.ts
- server/src/routes/Projects.ts
- server/src/routes/Search.ts
- server/src/routes/System.ts
- server/src/routes/Users.ts
- server/src/util.ts
- server/test/Entities_API.test.ts
- server/test/Projects.test.ts
- types/index.d.ts
adding entity tests and permissions checks
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/240/
> [MARS-240] adding entity tests and permissions checks

- client/src/App.tsx
- client/src/util.ts
- client/src/variables.ts
- client/webpack.dev.js
replace REACT_APP_NODE_ENV to NODE_ENV
> [MARS-265] change env var

- server/src/operations/Authentication.ts
- server/src/routes/Attributes.ts
attribute owner under development mode was missing
[Please include link to Jira/AzureDevops etc
](https://dev.azure.com/gt-sse-center/MARS%202023/_sprints/backlog/MARS%202023%20Team/MARS%202023/Sprint%209?workitem=281)
> add owner to attribute

- client/src/pages/Search.tsx
- server/src/operations/Entities.ts
- server/src/routes/Entities.ts
make-regular-search-query-look-entities-and-attributes
https://dev.azure.com/gt-sse-center/MARS%202023/_sprints/backlog/MARS%202023%20Team/MARS%202023/Sprint%209?workitem=281
> [MARS-293] make-regular-search-query-look-entities-and-attributes

- client/src/components/DataTable/index.tsx
- client/src/components/Importer/index.tsx
- client/src/pages/view/Entities.tsx
- client/src/pages/view/Entity.tsx
- cypress/e2e/2_1_import_CSV.spec.cy.ts
- server/src/operations/Entities.ts
- server/src/operations/System.ts
- types/index.d.ts
* Base changes include updated Importer UI
* Remove tab interface, disable importing system backup
* Update some language
* Update drag-drop interface appearance
* Rely on MIME-type detection for determining imported file type
* Additional changes include bugfixes for JSON import and export
* JSON import and export formats now consistent across individual and bulk exports
* Small UI enhancements around export
* Update `DataTable` actions to add flag always enabling actions
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/292
> [MARS-292] Add language signifying CSV and JSON import functionality

- client/src/components/Importer/index.tsx
- client/src/components/Label/index.tsx
- server/src/operations/System.ts
* Add new `Information` label type
* Place `Information` label on the importer interface when dates can be mapped
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/294
> [MARS-294] Add warning on import for invalid date formats

- client/src/components/SearchBox/index.tsx
* Fixed by copying most of the existing search functionality from the text search page (`/search`) into the `SearchBox` component
* Added a footer to the `Popover` component containing a link to the text search page
* Small UI changes to search results
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/297
> [MARS 297] Quick search component makes bad request on search leading to error

- client/src/pages/view/Entity.tsx
add creation attribute template link in add attribute page
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/298
> [MARS-298] add creation attribute template link in add attribute page

- client/src/components/Navigation/index.tsx
- client/src/pages/view/Attributes.tsx
rename attribute to template attribute
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/302
> [MARS-302] rename attribute to template attribute

- client/src/components/AccountMenu/index.tsx
- client/src/pages/Dashboard.tsx
- client/src/pages/create/Create.tsx
* Quick and easy updates to Activity panel
* Small spacing adjustments to `AccountMenu`
* Add colons to labels for consistency
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/309
> [MARS 309] Improve design of Activity panel and fix responsive UI on dashboard

- client/src/components/Importer/index.tsx
- cypress/e2e/2_1_import_CSV.spec.cy.ts
- cypress/e2e/2_2_import_JSON.spec.cy.ts
* Reduced the number of `Modal` components to one single component. Extended UI state to include additional states.
* Refactored logic between JSON and CSV imports to enable the above change.
* Created event handler for Continue button, and added `useEffect` calls to update the state of the button depending on context.
* Added text, form helper text, and tooltips throughout.
* Updated Cypress tests to work with new CSS selectors.
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/304/
> [MARS 304] Add affordances to improve clarity of import workflow

- client/src/pages/view/Entity.tsx
- client/src/pages/view/Project.tsx
added cancel btn, moved delete btn
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/227
> [MARS-227] added cancel btn, moved delete btn

- client/src/pages/view/Entity.tsx
add feature save as template on add attribute
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/228/
> [MARS-228] add feature save as template on add attribute

- client/src/pages/view/Project.tsx
- server/src/operations/Projects.ts
- server/src/routes/Entities.ts
- server/src/routes/Projects.ts
- server/test/Projects.test.ts
- types/index.d.ts
invite by ORCiD stored in collaborators field in project
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/136/
> [MARS-136] invite by ORCiD stored in collaborators field in project

- server/src/operations/Authentication.ts
- server/src/operations/Projects.ts
on creation of new user, project and 2 entities and a template are created
https://dev.azure.com/gt-sse-center/MARS%202023/_workitems/edit/210/
> [MARS-210] on creation of new user, project and 2 entities and a template are created

- server/src/operations/Entities.ts
- server/src/operations/Projects.ts
- server/test/Entities.test.ts
- types/index.d.ts
add timestamp on Entity creation
https://dev.azure.com/gt-sse-center/MARS%202023/_sprints/taskboard/MARS%202023%20Team/MARS%202023/Sprint%2011?workitem=307
> [MARS-307] add timestamp on Entity creation

- .github/workflows/deploy.yml
Enable deployment of the server at the same time the client is deployed.
Jira: https://ccdresearch.atlassian.net/browse/MARS-1001
> [MARS-1001] Updating deployment workflow to include server with client

- .github/workflows/build_and_test.yml
- .github/workflows/deploy.yml
Updated GitHub Actions files to build the server and deploy correctly. Updated `deploy.yml` to build the server, upload the build artifact, then download the artifact in a deploy step.
https://ccdresearch.atlassian.net/browse/MARS-1008
> MARS-1008 Missing `index.js` after server deployment

- client/src/components/SearchQueryValue/index.tsx
- client/src/components/SearchSelect/index.tsx
- client/src/components/Values/index.tsx
- client/src/pages/view/Entity.tsx
- client/src/pages/view/Project.tsx
- types/index.d.ts
Fix issue where React state was not being updated to parent components that used the `SearchSelect` component.
https://ccdresearch.atlassian.net/browse/MARS-1020
> MARS-1020-Unable-to-edit-Entity-type-Values

- client/src/components/SearchSelect/index.tsx
- client/src/pages/view/Project.tsx
Enable Entities to be removed directly from a Project. Entities can be removed individually or bulk selected and removed.
> MARS-64-Fix-removing-Entities-from-Project

- client/package.json
- client/src/components/PreviewModal/index.tsx
- client/src/pages/view/Entity.tsx
- client/yarn.lock
- server/src/index.ts
- types/index.d.ts
Integrate a new library to enable zooming and panning when previewing image attachments.
https://ccdresearch.atlassian.net/browse/MARS-63
> MARS-63-Zooming-and-panning-image-previews-does-not-function-as-expected

- README.md
- client/src/components/Error/index.tsx
- client/src/components/Navigation/index.tsx
- client/src/components/WorkspaceCreateModal/index.tsx
- client/src/components/WorkspaceUpdateModal/index.tsx
- client/src/index.html
- client/src/pages/Invalid.tsx
- client/src/pages/Login.tsx
- client/src/pages/create/Project.tsx
- client/src/pages/view/Entity.tsx
- client/src/pages/view/Project.tsx
- client/src/variables.ts
- client/webpack.common.js
- server/src/index.ts
- server/src/models/Authentication.ts
Rebranded application to `Metadatify` to use a more SEO-friendly name, also reflecting the application purpose.
https://ccdresearch.atlassian.net/browse/MARS-1031
> MARS-1031-Rebrand-to-metadatify

- client/src/components/SearchSelect/index.tsx
Added existing options to be visible when first opening the `SearchSelect` component. Remove unnecessary text and added information when no results are returned.
https://ccdresearch.atlassian.net/browse/MARS-1030
> MARS-1030-Improve-SearchSelect-UI-by-adding-existing-options

- client/src/pages/create/Entity.tsx
Add `SearchSelect` component in place of standard `Select` components when selecting Entities.
https://ccdresearch.atlassian.net/browse/MARS-1033
> MARS-1033-Integrate-SearchSelect-into-all-other-instances-where-Entities-selected

- client/src/components/AccountMenu/index.tsx
- client/src/components/PreviewModal/index.tsx
- client/src/pages/view/Entity.tsx
- types/index.d.ts
Some images and documents were not being shown in the `PreviewModal` component.
https://ccdresearch.atlassian.net/browse/MARS-1026
> MARS-1026-Images-not-being-shown-in-Entity-attachments

- client/src/App.tsx
- client/src/components/AccountMenu/index.tsx
- client/src/components/Icon/index.tsx
- client/src/pages/Dashboard.tsx
- client/src/pages/Login.tsx
- client/src/pages/create/Workspace.tsx
- client/src/pages/view/User.tsx
- cypress/e2e/1_launch.spec.cy.ts
- server/src/models/Authentication.ts
- server/src/models/Users.ts
- server/src/resolvers/Users.ts
- server/src/resolvers/Workspaces.ts
- server/src/typedefs.ts
- types/index.d.ts
Require user information to be provided on first login. Add a `/profile` endpoint allowing users to customise information.
https://ccdresearch.atlassian.net/browse/MARS-1027
> MARS-1027-Define-user-first-name-last-name-and-email-address-on-first-login

- client/src/components/DataTable/index.tsx
- client/src/components/Icon/index.tsx
- client/src/pages/Dashboard.tsx
- client/src/pages/view/Attribute.tsx
- client/src/pages/view/Attributes.tsx
- client/src/pages/view/Entities.tsx
- client/src/pages/view/Project.tsx
- client/src/pages/view/Projects.tsx
- client/src/pages/view/Workspace.tsx
- types/index.d.ts
Add refresh capability to Dashboard page.
https://ccdresearch.atlassian.net/browse/MARS-1044
> MARS-1044-Dashboard-auto-refresh-component

- client/src/components/AccountMenu/index.tsx
- client/src/components/Importer/index.tsx
- client/src/components/Values/index.tsx
- client/src/components/WorkspaceSwitcher/index.tsx
- client/src/pages/Dashboard.tsx
- client/src/pages/create/Entity.tsx
- client/src/pages/create/Project.tsx
- client/src/pages/view/Attribute.tsx
- client/src/pages/view/Entities.tsx
- client/src/pages/view/Entity.tsx
- client/src/pages/view/Project.tsx
- client/src/pages/view/User.tsx
- client/src/pages/view/Workspace.tsx
- server/src/models/Entities.ts
- server/src/models/Projects.ts
- server/src/resolvers/Entities.ts
- server/src/resolvers/Projects.ts
- server/src/typedefs.ts
- server/test/Entities.test.ts
- types/index.d.ts
Enable history for Entities and Projects. Apply small UI updates and server enhancements as encountered.
https://ccdresearch.atlassian.net/browse/MARS-1039
> MARS-1039-Enable-version-history-for-Workspace-contents

- client/src/components/Container/index.tsx
- client/src/hooks/useAuthentication/index.tsx
- client/src/pages/Login.tsx
- server/src/models/Authentication.ts
* Fix small state-related issues that became apparent in production deployment of refactored login workflow.
* Fixed redirect URIs that had not been updated.
* Ensure `isAuthenticated` is updated via `useMemo`.
* Set the `token` before attempting to retrieve the `UserModel`, avoiding any authentication errors.
https://ccdresearch.atlassian.net/browse/MARS-1057
> MARS-1057-Resolve-login-bug-in-production-deployment

- client/src/components/Graph/index.tsx
- cypress/e2e/2_1_import_CSV.spec.cy.ts
- cypress/e2e/2_2_import_JSON.spec.cy.ts
* Update the design of the `Graph` component and the displayed nodes
https://ccdresearch.atlassian.net/browse/MARS-1058
> MARS-1058-Redesign-graph-nodes-and-structures

- client/src/components/SearchQueryBuilder/index.tsx
- client/src/components/SearchQueryValue/index.tsx
- client/src/components/Values/index.tsx
- client/src/pages/Search.tsx
- types/index.d.ts
* Initial support for querying Attributes and their values.
https://ccdresearch.atlassian.net/browse/MARS-1046
> MARS-1046-Update-QueryBuilder-to-include-fields-for-Attribute-types-and-data

- client/src/pages/Login.tsx
* Resolves a missing UI affordance where the login button would not reflect the loading state.
https://ccdresearch.atlassian.net/browse/MARS-1060
> MARS-1060-Login-button-not-reflecting-loading-state

- README.md
- client/src/components/WorkspaceSwitcher/index.tsx
- client/test/cypress/tests/security/endpoints.spec.cy.ts
* Add initial set of security integration tests. Use Cypress to logout and test that endpoints are not accessible.
https://ccdresearch.atlassian.net/browse/MARS-1062
> MARS-1062-Add-security-integration-tests

- server/src/index.ts
- server/src/models/API.ts
- server/src/models/Authentication.ts
- server/src/models/Users.ts
- server/test/util.ts
- types/index.d.ts
* Added `POST` request for `entity`, allowing user to update Entity based on contents in body of request
https://ccdresearch.atlassian.net/browse/MARS-1064
> MARS-1064-Add-new-paths-for-API

- client/package.json
- client/src/components/ActorTag/index.tsx
- client/src/components/AttributeCard/index.tsx
- client/src/components/AttributeViewButton/index.tsx
- client/src/pages/create/Attribute.tsx
- client/src/pages/create/Entity.tsx
- client/src/pages/create/Project.tsx
- client/src/pages/create/Workspace.tsx
- client/src/pages/view/Attribute.tsx
- client/src/pages/view/Entity.tsx
- client/src/pages/view/Project.tsx
- client/src/pages/view/Workspace.tsx
- client/yarn.lock
- server/src/models/Workspaces.ts
* Replace existing description fields with a Markdown-supported input field
https://ccdresearch.atlassian.net/browse/MARS-1065
> MARS-1065-Use-Markdown-enabled-field-for-all-descriptions

- client/src/components/ImportModal/index.tsx
- client/src/components/Navigation/index.tsx
- client/src/components/ScanModal/index.tsx
- types/index.d.ts
* Add a new `ScanModal` component to enable receiving input from a scanner or optionally manually enter the identifier.
https://ccdresearch.atlassian.net/browse/MARS-1068
> MARS-1068-Add-new-Scan-modal-to-accept-input-from-external-scanners

- client/src/components/DataTable/index.tsx
- client/src/components/ImportModal/index.tsx
- templates/migrations/associations2relationships.py
- templates/validate.py
- types/index.d.ts
* After reviewing the scope of work required for this feature, it was deemed somewhat redundant as the user should simply remove the Entity manually from the import file instead.
* Added new prop to `DataTable` allowing a callback to receive the list of selected rows, as this could be a useful feature.
https://ccdresearch.atlassian.net/browse/MARS-1071
> MARS-1071-Import-review-page-allows-inclusion-and-exclusion-of-updates

- client/src/components/SearchSelect/index.tsx
- client/src/pages/create/Project.tsx
- client/src/pages/view/Project.tsx
- server/src/models/Projects.ts
- server/src/models/Search.ts
* Entities can be added from the Project creation page.
* Updated basic text search to prioritize results by their "relevance", where the relevance is based on the matching with the name of the Entity.
https://ccdresearch.atlassian.net/browse/MARS-1017
> MARS-1017-Add-Select-Entities-section-to-Project-creation-page

- .github/workflows/main-deploy-server.yml
- .github/workflows/main-pr-build-test.yml
- client/package.json
- client/src/components/ImportModal/index.tsx
- client/src/components/Navigation/index.tsx
- client/src/components/ScanModal/index.tsx
- client/src/hooks/useAuthentication/index.tsx
- client/src/index.tsx
- client/src/pages/Invalid.tsx
- client/src/pages/Login.tsx
- client/src/pages/create/Create.tsx
- client/src/pages/create/Entity.tsx
- client/src/pages/create/Project.tsx
- client/src/pages/create/Template.tsx
- client/src/pages/create/Workspace.tsx
- client/webpack.common.js
- client/yarn.lock
- server/package.json
- server/src/index.ts
- server/src/resolvers/Activity.ts
- server/src/resolvers/Entities.ts
- server/src/resolvers/Projects.ts
- server/src/resolvers/Templates.ts
- server/src/resolvers/Workspaces.ts
- server/yarn.lock
* Integrate Posthog with the client and server.
* Add custom events for most CRUD operations.
* Add custom events for scanner and import modals.
https://ccdresearch.atlassian.net/browse/MARS-1067
> MARS-1067-Integrate-observability-platforms-for-metrics-and-monitoring

- .github/workflows/main-deploy-client.yml
- .github/workflows/main-pr-build-test.yml
* Fix client integration with PostHog.
https://ccdresearch.atlassian.net/browse/MARS-1077
> MARS-1077-PostHog-not-capturing-client-events

- client/eslint.config.mjs
- client/src/components/ImportModal/index.tsx
- client/src/hooks/useAuthentication/index.tsx
- server/eslint.config.mjs
- server/src/models/API.ts
- server/src/models/Authentication.ts
- server/src/models/Data.ts
- server/src/models/Entities.ts
- server/src/models/Projects.ts
- server/src/resolvers/API.ts
- server/src/resolvers/Activity.ts
- server/src/resolvers/Authentication.ts
- server/src/resolvers/Data.ts
- server/src/resolvers/Entities.ts
- server/src/resolvers/Projects.ts
- server/src/resolvers/Search.ts
- server/src/resolvers/Templates.ts
- server/src/resolvers/Users.ts
- server/src/resolvers/Workspaces.ts
- types/index.d.ts
* Refactor how files are checked and handled by `ImportModal`
* Add new errors and pre-import validation
* Add new types for GraphQL resolvers and models
https://ccdresearch.atlassian.net/browse/MARS-1078
> MARS-1078-Improve-import-file-validation-and-error-handling

- client/package.json
- client/src/components/WalkthroughBeacon/index.tsx
- client/src/components/WalkthroughTooltip/index.tsx
- client/src/hooks/useAuthentication/index.tsx
- client/src/pages/Dashboard.tsx
- client/yarn.lock
- types/index.d.ts
* Add a walkthrough upon first login.
* Add a `firstLogin` flag to the stored token.
https://ccdresearch.atlassian.net/browse/MARS-1082
> MARS-1082-User-presented-with-tutorial-or-walkthrough-on-first-login

- client/package.json
- client/src/components/ImportModal/index.tsx
- client/yarn.lock
- server/src/models/Data.ts
- server/src/resolvers/Data.ts
- server/src/typedefs.ts
* Fixed bug when importing JSON files where Attributes created during import would not be added to each Entity.
* Validated bug resolved for both creating and updating Entities using JSON files.
https://ccdresearch.atlassian.net/browse/MARS-1081
> MARS-1081-Updating-Entity-via-JSON-does-not-add-new-Attributes-correctly

- client/package.json
- client/src/components/ScanModal/index.tsx
- client/src/components/Scanner/index.tsx
- client/yarn.lock
- types/index.d.ts
* Created new `Scanner` component using the `html5-qrcode` library. Users can elect to give camera permission and scan QR codes with their devices.
* Updated types and integrated with existing `ScanModal` component.
https://ccdresearch.atlassian.net/browse/MARS-1085
> MARS-1085-Add-experimental-in-browser-QR-code-scanning

- client/src/components/AttributeCard/index.tsx
- client/src/components/Navigation/index.tsx
- client/src/components/WorkspaceSwitcher/index.tsx
- client/src/pages/Dashboard.tsx
- client/src/pages/Search.tsx
- client/src/pages/create/Entity.tsx
- client/src/pages/create/Project.tsx
- client/src/pages/create/Template.tsx
- client/src/pages/create/Workspace.tsx
- client/src/pages/view/Entity.tsx
- client/src/pages/view/Project.tsx
- client/src/pages/view/User.tsx
- client/src/pages/view/Workspace.tsx
- client/test/cypress/tests/security/endpoints.spec.cy.ts
* Fix responsive behavior on smaller screens.
* Add scan button and Workspace switcher component to mobile navigation menu.
* Fix many issues with flex wrapping and filling.
https://ccdresearch.atlassian.net/browse/MARS-1086
> MARS-1086-Update-responsive-UI-to-include-all-navigation-menu-items

- client/cypress.config.ts
- client/src/components/ActorTag/index.tsx
- client/src/components/AttributeViewButton/index.tsx
- client/src/components/Navigation/index.tsx
- client/src/components/PreviewModal/index.tsx
- client/src/components/VisibilityTag/index.tsx
- client/src/pages/Dashboard.tsx
- client/src/pages/Login.tsx
- client/src/pages/Setup.tsx
- client/src/pages/view/Entity.tsx
- client/src/pages/view/Project.tsx
- client/src/pages/view/Templates.tsx
- client/src/pages/view/User.tsx
- client/src/styles/styles.css
- client/test/cypress/support/database.ts
- client/test/cypress/tests/launch.spec.cy.ts
- client/test/cypress/tests/security/endpoints.spec.cy.ts
- client/test/cypress/tests/ui/entity/entity_edit_attribute.spec.cy.ts
- client/test/cypress/tests/ui/entity/entity_edit_details.spec.cy.ts
- client/test/cypress/tests/ui/import/import_csv.spec.cy.ts
- client/test/cypress/tests/ui/import/import_json.spec.cy.ts
- client/test/cypress/tests/ui/project/project_edit_details.spec.cy.ts
- client/test/cypress/tests/ui/project/project_edit_entities.spec.cy.ts
- client/test/cypress/tests/ui/query/build_query.spec.cy.ts
- server/src/resolvers/Data.ts
- server/test/util.ts
* Identified some issues with responsive behavior, updated to address most critical UI issues.
https://ccdresearch.atlassian.net/browse/MARS-1087
> MARS-1087-Identify-and-resolve-remaining-issues-with-responsive-UI

- client/package.json
- client/src/components/ActorTag/index.tsx
- client/src/components/DataTable/index.tsx
- client/src/components/ImportModal/index.tsx
- client/src/components/Label/index.tsx
- client/src/components/SearchQueryBuilder/index.tsx
- client/src/components/SearchQueryValue/index.tsx
- client/src/pages/Dashboard.tsx
- client/src/pages/Search.tsx
- client/src/pages/view/Entities.tsx
- client/src/pages/view/Entity.tsx
- client/src/pages/view/Project.tsx
- client/src/pages/view/Projects.tsx
- client/src/pages/view/Templates.tsx
- client/src/styles/styles.css
- client/test/cypress/tests/ui/query/build_query.spec.cy.ts
- client/yarn.lock
- server/package.json
- server/src/models/Data.ts
- server/src/models/Entities.ts
- server/src/models/Search.ts
- server/src/resolvers/Entities.ts
- server/src/typedefs.ts
- server/yarn.lock
* Fix various bugs impacting the number of Entities being presented in on the Entities view page.
* Add new `Information` label across application.
* Add ability to specify a prefix before each Entity name on import.
https://ccdresearch.atlassian.net/browse/MARS-1093
> MARS-1093-GraphQL-not-showing-all-Entities

- client/package.json
- client/src/components/PreviewModal/index.tsx
- client/src/components/Uploader/index.tsx
- client/src/pages/view/Entity.tsx
- client/yarn.lock
- types/index.d.ts
* Add ability to view `.dna` files in the `PreviewModal` component.
* Use `seqviz` to read and display preview.
https://ccdresearch.atlassian.net/browse/MARS-1091
> MARS-1091-Preview-support-for-.dna-files

- client/src/pages/Dashboard.tsx
- server/package.json
- server/yarn.lock
* Fixed issue on `Dashboard` page causing overflow on mobile devices.
* Added "watch" build functionality to server.
https://ccdresearch.atlassian.net/browse/MARS-1100
> MARS-1100-Dashboard-Entities-table-overflowing-view

- client/src/pages/view/Entities.tsx
- server/src/models/Entities.ts
- server/src/resolvers/Entities.ts
- server/src/typedefs.ts
* Added a modal to `Entities` page when `Export Selected` is clicked from the `Actions` menu.
* Added a `format` parameter to the `exportEntities` function allowing a format to be specified.
https://ccdresearch.atlassian.net/browse/MARS-1105
> MARS-1105-Allow-export-of-multiple-Entity-IDs-via-CSV

- client/src/pages/view/Entity.tsx
- server/src/models/Entities.ts
* Fix a bug where the Entity import steps would crash on the "Review" page when importing a JSON file.
https://ccdresearch.atlassian.net/browse/MARS-1113
> MARS-1113-Crash-on-Review-page-during-JSON-import-of-single-Entity

- client/src/components/AttributeCard/index.tsx
- client/src/components/AttributeViewButton/index.tsx
- client/src/components/Container/index.tsx
- client/src/components/DataTable/index.tsx
- client/src/components/SearchSelect/index.tsx
- client/src/components/Values/index.tsx
- client/src/pages/create/Entity.tsx
- client/src/pages/create/Project.tsx
- client/src/pages/create/Template.tsx
- client/src/pages/view/Entity.tsx
- client/src/pages/view/Project.tsx
- client/test/cypress/tests/ui/entity/entity_create_workflow.spec.cy.ts
- client/test/cypress/tests/ui/entity/entity_edit_attribute.spec.cy.ts
- client/test/cypress/tests/ui/project/project_create_workflow.spec.cy.ts
* Fix UI issues with `AttributeCard` and other `Attribute`-related components
* Update Cypress tests
https://ccdresearch.atlassian.net/browse/MARS-1117
> MARS-1117-Fix-appearance-and-padding-of-AttributeCard

- client/src/hooks/useWorkspace/index.tsx
- client/src/index.tsx
* Clear GraphQL data on Workspace change
* Add better error handling for client GraphQL
https://ccdresearch.atlassian.net/browse/MARS-1114
> MARS-1114-GraphQL-data-preserved-between-Workspaces

- client/src/pages/Dashboard.tsx
- client/src/pages/Login.tsx
- client/src/pages/Setup.tsx
- client/src/pages/view/Workspace.tsx
- client/src/util.ts
- server/src/resolvers/Projects.ts
- server/src/typedefs.ts
* Fixed bug where archived Projects were still visible in the Workspace
* Updated Login and Setup UI
https://ccdresearch.atlassian.net/browse/MARS-1115
> MARS-1115-Archived-Project-still-visible-within-Workspace
